# Merval

In [4]:
import pandas as pd
import numpy as np

# Cargamos los datos del índice desde el archivo .csv
data = pd.read_csv("merval.csv")

# Veamos los últimos datos
data.head()

Fecha     Último   Apertura     Máximo     Mínimo Vol.  % var.
0  02.08.2019  41.359,15  41.410,98  41.651,40  40.572,68    -  -0,13%
1  01.08.2019  41.410,98  42.057,77  42.492,78  41.220,28    -  -1,54%
2  31.07.2019  42.057,77  42.463,24  42.722,32  41.804,62    -  -0,95%
3  30.07.2019  42.463,24  42.785,46  42.836,75  42.417,96    -  -0,75%
4  29.07.2019  42.785,46  41.983,74  43.069,98  41.743,16    -   1,91%

In [5]:
# Cantidad de muestras (días) que tenemos del índice MERVAL
len(data)

2449

In [6]:
# Necesitamos convertir cada variación a float para poder analizar los datos ya que eran strings.
data["% var."] = data["% var."].apply(lambda x: float(x.replace(",",".")[0:-1]))

In [7]:
# Días que el Merval se mantuvo estacionario
# Cantidad de estados (S)
data[data["% var."] == 0]["% var."].count()

22

In [8]:
# Días que el Merval subió
# Cantidad de estados (U)
data[data["% var."] > 0]["% var."].count()

1312

In [9]:
# Días que el Merval bajó
# Cantidad de estados (D)
data[data["% var."] < 0]["% var."].count()

1115

In [10]:
# Necesitamos saber la correlación de estados, es decir, en que estado estaba y a cual se movió
# Para poder armar luego la matriz de transición
# Para esto necesitamos saber en que estado estamos y cual fue el anterior
conditions = [
    (data["% var."] > 0),
    (data["% var."] < 0),
    (data["% var."] == 0)
]
choices = ["U", "D", "S"]
data["Actual"] = np.select(conditions, choices, default="black")

In [11]:
# Ya tenemos una columna con el estado actual
data.head()

Fecha     Último   Apertura     Máximo     Mínimo Vol.  % var. Actual
0  02.08.2019  41.359,15  41.410,98  41.651,40  40.572,68    -   -0.13      D
1  01.08.2019  41.410,98  42.057,77  42.492,78  41.220,28    -   -1.54      D
2  31.07.2019  42.057,77  42.463,24  42.722,32  41.804,62    -   -0.95      D
3  30.07.2019  42.463,24  42.785,46  42.836,75  42.417,96    -   -0.75      D
4  29.07.2019  42.785,46  41.983,74  43.069,98  41.743,16    -    1.91      U

In [12]:
for i in range(1, len(data)):
    data.loc[i-1, "Anterior"] = data.loc[i, "Actual"]

In [13]:
# Ahora ya tenemos en cada estado cual fue el anterior, ya tenemos todos los datos para calcular nuestra matriz
data.head()

Fecha     Último   Apertura     Máximo     Mínimo Vol.  % var. Actual  \
0  02.08.2019  41.359,15  41.410,98  41.651,40  40.572,68    -   -0.13      D   
1  01.08.2019  41.410,98  42.057,77  42.492,78  41.220,28    -   -1.54      D   
2  31.07.2019  42.057,77  42.463,24  42.722,32  41.804,62    -   -0.95      D   
3  30.07.2019  42.463,24  42.785,46  42.836,75  42.417,96    -   -0.75      D   
4  29.07.2019  42.785,46  41.983,74  43.069,98  41.743,16    -    1.91      U   

  Anterior  
0        D  
1        D  
2        D  
3        U  
4        U

In [14]:
# Procedemos a obtener los datos para armar la matriz
# Cantidad de transiciones del estado U al estado U.

data[(data["Anterior"] == "U") & (data["Actual"] == "U")].count()

Fecha       736
Último      736
Apertura    736
Máximo      736
Mínimo      736
Vol.        736
% var.      736
Actual      736
Anterior    736
dtype: int64

In [15]:
# Cantidad de transiciones del estado U al estado S.
data[(data["Anterior"] == "U") & (data["Actual"] == "S")].count()

Fecha       15
Último      15
Apertura    15
Máximo      15
Mínimo      15
Vol.        15
% var.      15
Actual      15
Anterior    15
dtype: int64

In [16]:
# Cantidad de transiciones del estado U al estado D.
data[(data["Anterior"] == "U") & (data["Actual"] == "D")].count()

Fecha       561
Último      561
Apertura    561
Máximo      561
Mínimo      561
Vol.        561
% var.      561
Actual      561
Anterior    561
dtype: int64

In [17]:
# Cantidad de transiciones del estado S al estado U.
data[(data["Anterior"] == "S") & (data["Actual"] == "U")].count()

Fecha       11
Último      11
Apertura    11
Máximo      11
Mínimo      11
Vol.        11
% var.      11
Actual      11
Anterior    11
dtype: int64

In [18]:
# Cantidad de transiciones del estado S al estado S.
data[(data["Anterior"] == "S") & (data["Actual"] == "S")].count()

Fecha       1
Último      1
Apertura    1
Máximo      1
Mínimo      1
Vol.        1
% var.      1
Actual      1
Anterior    1
dtype: int64

In [19]:
# Cantidad de transiciones del estado S al estado D.
data[(data["Anterior"] == "S") & (data["Actual"] == "D")].count()

Fecha       10
Último      10
Apertura    10
Máximo      10
Mínimo      10
Vol.        10
% var.      10
Actual      10
Anterior    10
dtype: int64

In [20]:
# Cantidad de transiciones del estado D al estado U.
data[(data["Anterior"] == "D") & (data["Actual"] == "U")].count()

Fecha       565
Último      565
Apertura    565
Máximo      565
Mínimo      565
Vol.        565
% var.      565
Actual      565
Anterior    565
dtype: int64

In [21]:
# Cantidad de transiciones del estado D al estado S.
data[(data["Anterior"] == "D") & (data["Actual"] == "S")].count()

Fecha       6
Último      6
Apertura    6
Máximo      6
Mínimo      6
Vol.        6
% var.      6
Actual      6
Anterior    6
dtype: int64

In [22]:
# Cantidad de transiciones del estado D al estado D.
data[(data["Anterior"] == "D") & (data["Actual"] == "D")].count()

Fecha       543
Último      543
Apertura    543
Máximo      543
Mínimo      543
Vol.        543
% var.      543
Actual      543
Anterior    543
dtype: int64

In [23]:
# Ya podemos armar la matriz de cantidad de estados

matriz_estados = np.matrix([[736,15,561], [11, 1, 10], [565, 6, 543]])
matriz_estados

matrix([[736,  15, 561],
        [ 11,   1,  10],
        [565,   6, 543]])

In [24]:
# Calculamos las probabilidades y obtenemos la matriz de transición

matriz_transiciones = matriz_estados * 1/matriz_estados.sum(1)
matriz_transiciones

matrix([[0.56097561, 0.01143293, 0.42759146],
        [0.5       , 0.04545455, 0.45454545],
        [0.50718133, 0.005386  , 0.48743268]])

In [50]:
# Para obtener las probabilidades de los estados inciales
# dividimos la suma de las ocurrencias de cada estados por la cantidad total de estados

p_U_0 = (736 + 15 + 561) / 2449
p_S_0 = (11 + 1 + 10) / 2449
p_D_0 = (565 + 6 + 543) / 2449

In [51]:
estado_inicial = np.matrix([p_U_0, p_S_0, p_D_0])

In [52]:
estado_inicial

matrix([[0.53572887, 0.00898326, 0.45487954]])

In [61]:
# Si comenzamos en el estado U las probabilidades al cabo de 5 dias quedan

np.matrix([1, 0, 0]) * matriz_transiciones ** 5

matrix([[0.5359479 , 0.008987  , 0.45506511]])

In [62]:
# Si comenzamos en el estado S las probabilidades al cabo de 5 dias quedan

np.matrix([0, 1, 0]) * matriz_transiciones ** 5

matrix([[0.53594733, 0.00898691, 0.45506576]])

In [63]:
# Si comenzamos en el estado D las probabilidades al cabo de 5 dias quedan

np.matrix([0, 0, 1]) * matriz_transiciones ** 5

matrix([[0.5359475 , 0.00898685, 0.45506565]])

In [65]:
# Para saber el estado asintotico multiplicamos la matriz de transicion reiteradas veces

matriz_transiciones ** 999

matrix([[0.53594771, 0.00898693, 0.45506536],
        [0.53594771, 0.00898693, 0.45506536],
        [0.53594771, 0.00898693, 0.45506536]])

In [70]:
# Cantidad de días dentro de 5 dias que esperariamos que el indice suba
5 * 0.53594771

2.6797385499999997

In [71]:
# Cantidad de días dentro de 5 dias que esperariamos que el indice se mantenga estacionario
5 * 0.00898693

0.04493465000000001

In [72]:
# Cantidad de días dentro de 5 dias que esperariamos que el indice baje
5 * 0.45506536

2.2753267999999998

In [75]:
# Tiempo que esperaríamos que tarde en salir de una suba hasta que vuelva a subir el indice
1 / 0.56097561

1.7826086948771267

In [76]:
# Tiempo que esperaríamos que tarde en salir de un estado estacionario hasta que vuelva a estar estacionario
1 / 0.04545455

21.99999780000022

In [77]:
# Tiempo que esperaríamos que tarde en salir de una baja hasta que vuelva a bajar el indice
1 / 0.48743268

2.0515653566765364